# MySQL connection
mysql:
  host: 127.0.0.1
  port: 3306
  dbname: "duels"
  username: "root"
  password: ""

queue-premium-enabled: true

# Button text of the kits
placeHolders:
  SG: "&bSG\n&8{0} Queue | {1} Playing"

# Lobby options
lobby-items-enabled: false
# Items
lobby-items:
  join-queue-unranked:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lQueue Unranked"
    command: "queue list unranked"
    slot: 1
  join-queue-ranked:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lQueue Ranked"
    command: "queue list ranked"
    slot: 1
  leave-queue:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lLeave queue"
    command: "queue leave"
    slot: 8

# Spectator options
spectator-items-enabled: false
# Items
spectator-items:
  leave:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lLeave"
    command: "leave"
    slot: 8