# MySQL connection
mysql:
  host: 127.0.0.1
  port: 3306
  dbname: "duels"
  username: "root"
  password: ""

# Enable/disable the queue premium
queue-premium-enabled: true

# Button text of the kits
placeHolders:
  SG: "&bSG\n&8{0} Queue | {1} Playing"

# Lobby options
lobby-items-enabled: false
# Items
lobby-items:
  join-queue-unranked:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lQueue Unranked"
    commands:
      - name: "queue list unranked"
        console: false
    slot: 0
  join-queue-ranked:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lQueue Ranked"
    commands:
      - name: "queue list ranked"
        console: false
    slot: 1
  leave-queue:
    id: 355
    meta: 14
    count: 1
    name: "&r&c&lLeave queue"
    commands:
      - name: "queue leave"
        console: false
    slot: 8

form-title-duel: "DUEL KIT SELECTION"
form-content-duel: "Select a kit"

message-stats-players: "Stats of {0}\nWins: {1}\nLosses: {2}"